# Generated by Django 5.2.4 on 2025-07-14 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_kor", models.CharField(max_length=255)),
                ("title_eng", models.CharField(max_length=255)),
                ("poster_url", models.URLField()),
                ("genre", models.CharField(max_length=255)),
                ("showtime", models.CharField(max_length=50)),
                ("release_date", models.CharField(max_length=50)),
                ("plot", models.TextField()),
                ("rating", models.CharField(max_length=10)),
                ("director_name", models.CharField(max_length=255)),
                ("director_image_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("character", models.CharField(max_length=255)),
                ("image_url", models.URLField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actors",
                        to="movies.movie",
                    ),
                ),
            ],
        ),
    ]
