# Generated by Django 5.2.4 on 2025-07-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="rating",
        ),
        migrations.AddField(
            model_name="movie",
            name="audience_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="critic_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="netizen_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="showtime",
            field=models.IntegerField(max_length=50),
        ),
    ]
