# Generated by Django 5.2.4 on 2025-07-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_remove_movie_rating_movie_audience_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="showtime",
            field=models.IntegerField(),
        ),
    ]
